package daemon

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/multica-ai/multica/server/pkg/permissionprofile"
)

// Approval gates (K05), daemon side. Three interception points feed the
// same server flow (a Decision Card the run waits on):
//   - git pre-push: a hook directory the daemon owns, selected per run
//     through GIT_CONFIG_* so the repository's own hooks stay untouched;
//   - sensitive MCP tools: the remote MCP broker asks before forwarding;
//   - spend: the run requests a short-lived token from the server.
// The run never decides for itself whether to wait: the server does.

// DefaultGateSensitiveTools mirrors the server default and applies when the
// claim carries no pattern of its own — an older server, or a workspace read
// that failed. What is asked is decided by the workspace's own
// approval_gates.sensitive_tools, which travels on the claim: until it did,
// widening the pattern in workspace settings changed nothing, because the
// server was never asked about the tools it added.
const DefaultGateSensitiveTools = `(?i)merge|delete|remove|drop|destroy|pay|charge|transfer|refund|purchase`

const gateDefaultTimeout = 30 * time.Minute

// gateHookPrelude is shared by every hook the gate directory holds. Selecting
// that directory through core.hooksPath replaces the repository's own hooks
// for the whole run — the repo cache's Co-authored-by prepare-commit-msg, a
// project's commit-msg or pre-push — so each gate hook first finds the
// directory git would otherwise have used and runs the hook of the same name.
const gateHookPrelude = `#!/bin/sh
# Multica approval gate (K05). Generated by the Multica daemon; overwritten on
# every run.

# multica_original_hooks_dir prints the hooks directory git would use without
# the gate: core.hooksPath read without the gate's own GIT_CONFIG_* entry, or
# the common git dir's hooks/. It fails when that is the gate directory itself.
multica_original_hooks_dir() {
  multica_self=$(cd "$(dirname "$0")" && pwd -P) || return 1
  multica_dir=$(GIT_CONFIG_COUNT="${MULTICA_GATE_GIT_CONFIG_INDEX:-$GIT_CONFIG_COUNT}" git config --type=path core.hooksPath 2>/dev/null)
  if [ -z "$multica_dir" ] || [ "$(cd "$multica_dir" 2>/dev/null && pwd -P)" = "$multica_self" ]; then
    multica_common=$(git rev-parse --git-common-dir 2>/dev/null) || return 1
    multica_dir="$multica_common/hooks"
  fi
  [ "$(cd "$multica_dir" 2>/dev/null && pwd -P)" != "$multica_self" ] || return 1
  printf '%s' "$multica_dir"
}

# multica_original_hook prints the repository's executable hook of this name.
multica_original_hook() {
  multica_orig_dir=$(multica_original_hooks_dir) || return 1
  multica_hook="$multica_orig_dir/$(basename "$0")"
  [ -f "$multica_hook" ] && [ -x "$multica_hook" ] || return 1
  printf '%s' "$multica_hook"
}
`

// gateRelayHookScript runs the repository's own hook, stdin and arguments
// included, and succeeds when there is none.
const gateRelayHookScript = gateHookPrelude + `
multica_hook=$(multica_original_hook) || exit 0
exec "$multica_hook" "$@"
`

// gateRelayHooks are the hooks the gate directory relays. Hooks whose mere
// presence changes what git does (push-to-checkout, proc-receive) are left
// out: a relay standing in for a missing one would change behavior.
var gateRelayHooks = []string{
	"applypatch-msg", "pre-applypatch", "post-applypatch",
	"pre-commit", "pre-merge-commit", "prepare-commit-msg", "commit-msg", "post-commit",
	"pre-rebase", "post-checkout", "post-merge", "post-rewrite",
	"reference-transaction", "pre-auto-gc", "post-index-change", "sendemail-validate",
	"pre-receive", "update", "post-receive", "post-update",
	"p4-changelist", "p4-prepare-changelist", "p4-post-changelist", "p4-pre-submit",
}

// prePushHookScript runs the repository's own pre-push, then blocks a push to
// the watched remote until a human answers the gate. Any other remote (a
// personal fork) passes untouched.
//
// Every value sent to the server — remote, URL, refs, file names — is
// agent-controlled, so each is encoded as a JSON string (backslash and quote
// escaped, control characters dropped) rather than spliced into the body.
const prePushHookScript = gateHookPrelude + `
remote="$1"; url="$2"
MULTICA_HOOK_STDIN=$(cat)
if multica_hook=$(multica_original_hook); then
  { [ -z "$MULTICA_HOOK_STDIN" ] || printf '%s\n' "$MULTICA_HOOK_STDIN"; } | "$multica_hook" "$@" || exit $?
fi
[ -n "$MULTICA_TASK_ID" ] && [ -n "$MULTICA_TOKEN" ] && [ -n "$MULTICA_SERVER_URL" ] || exit 0
if [ -n "$MULTICA_GATE_REMOTE" ] && [ "$url" != "$MULTICA_GATE_REMOTE" ] && [ "$remote" != "$MULTICA_GATE_REMOTE" ]; then
  exit 0
fi
json_str() {
  printf '"%s"' "$(printf '%s' "$1" | tr -d '\000-\037' | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
}
refs=""
while read -r local_ref local_sha remote_ref remote_sha; do
  [ -n "$remote_ref" ] && refs="$refs $remote_ref"
done <<EOF_REFS
$(printf '%s\n' "$MULTICA_HOOK_STDIN")
EOF_REFS
refs=$(printf '%s' "$refs" | sed 's/^ //')
# Paths the push touches (K07 blast radius): the pushed commits' files, read
# NUL-separated so git does not C-quote unusual names, then one per line (a
# name with spaces stays one path) so each matches the project's patterns.
paths=""
while read -r local_ref local_sha remote_ref remote_sha; do
  [ -n "$local_sha" ] || continue
  case "$remote_sha" in
    0000000000000000000000000000000000000000|"") files=$(git diff-tree -z --root --no-commit-id --name-only -r "$local_sha" 2>/dev/null | tr '\000' '\n') ;;
    *) files=$(git diff -z --name-only "$remote_sha" "$local_sha" 2>/dev/null | tr '\000' '\n') ;;
  esac
  while IFS= read -r f; do
    [ -n "$f" ] && paths="$paths$(json_str "$f"),"
  done <<EOF_FILES
$files
EOF_FILES
done <<EOF_REFS
$(printf '%s\n' "$MULTICA_HOOK_STDIN")
EOF_REFS
paths="[${paths%,}]"
timeout="${MULTICA_GATE_TIMEOUT:-1800}"
api="${MULTICA_SERVER_URL%/}/api/tasks/$MULTICA_TASK_ID"
auth="Authorization: Bearer $MULTICA_TOKEN"
ws="X-Workspace-ID: $MULTICA_WORKSPACE_ID"
body=$(printf '{"gate_type":"git_push","summary":%s,"details":{"remote":%s,"url":%s,"refs":%s,"paths":%s}}' "$(json_str "git push $remote $refs")" "$(json_str "$remote")" "$(json_str "$url")" "$(json_str "$refs")" "$paths")
created=$(curl -sS -f -X POST "$api/gates" -H "$auth" -H "$ws" -H 'Content-Type: application/json' --data-binary "$body" 2>/dev/null) || { echo "multica: could not open the approval gate; push refused" >&2; exit 1; }
gate=$(printf '%s' "$created" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
[ -n "$gate" ] || { echo "multica: approval gate answer unreadable; push refused" >&2; exit 1; }
echo "multica: push to $remote $refs is waiting for a human approval (gate $gate)" >&2
start=$(date +%s)
while :; do
  now=$(date +%s)
  [ $((now - start)) -lt "$timeout" ] || { echo "multica: approval gate timed out; push refused" >&2; exit 1; }
  res=$(curl -sS -f "$api/gates/$gate?wait=25" -H "$auth" -H "$ws" 2>/dev/null) || { sleep 5; continue; }
  status=$(printf '%s' "$res" | sed -n 's/.*"status":"\([^"]*\)".*/\1/p')
  case "$status" in
    approved) echo "multica: push approved" >&2; exit 0 ;;
    denied)   echo "multica: push denied by a human; the run must not retry it" >&2; exit 1 ;;
    expired)  echo "multica: approval gate expired; push refused" >&2; exit 1 ;;
  esac
done
`

// ensureGateHooksDir writes the daemon's hook directory and returns it: the
// gating pre-push plus a relay for every other hook, so the repository's own
// hooks keep running while core.hooksPath points here.
func ensureGateHooksDir(configRoot string) (string, error) {
	dir := filepath.Join(configRoot, "hooks")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(dir, "pre-push"), []byte(prePushHookScript), 0o755); err != nil {
		return "", err
	}
	for _, name := range gateRelayHooks {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(gateRelayHookScript), 0o755); err != nil {
			return "", err
		}
	}
	return dir, nil
}

// gitRemoteURL is the origin of the run's checkout, empty when unknown.
func gitRemoteURL(dir string) string {
	if dir == "" {
		return ""
	}
	out, err := exec.Command("git", "-C", dir, "remote", "get-url", "origin").Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

// gateEnvironment selects the daemon hooks for every git call of the run
// and names the watched remote. The run inherits the daemon's environment, so
// an env-scoped git config already there (auth headers, URL rewrites) keeps
// its entries: the gate appends at the next index instead of claiming index 0,
// and records that index so its relays can read the config without it.
func gateEnvironment(hooksDir, remoteURL string, timeout time.Duration) map[string]string {
	index := 0
	if n, err := strconv.Atoi(os.Getenv("GIT_CONFIG_COUNT")); err == nil && n > 0 {
		index = n
	}
	idx := strconv.Itoa(index)
	return map[string]string{
		"GIT_CONFIG_COUNT":              strconv.Itoa(index + 1),
		"GIT_CONFIG_KEY_" + idx:         "core.hooksPath",
		"GIT_CONFIG_VALUE_" + idx:       hooksDir,
		"MULTICA_GATE_GIT_CONFIG_INDEX": idx,
		"MULTICA_GATE_REMOTE":           remoteURL,
		"MULTICA_GATE_TIMEOUT":          strconv.Itoa(int(timeout / time.Second)),
	}
}

// approvalGateClient asks the server on behalf of one run.
type approvalGateClient struct {
	serverURL string
	token     string
	taskID    string
	http      *http.Client
}

func newApprovalGateClient(serverURL, token, taskID string) *approvalGateClient {
	return &approvalGateClient{serverURL: strings.TrimRight(serverURL, "/"), token: token, taskID: taskID, http: &http.Client{Timeout: 40 * time.Second}}
}

func (c *approvalGateClient) do(ctx context.Context, method, path string, body any) (map[string]any, int, error) {
	var payload []byte
	if body != nil {
		payload, _ = json.Marshal(body)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.serverURL+path, bytes.NewReader(payload))
	if err != nil {
		return nil, 0, err
	}
	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	res, err := c.http.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer res.Body.Close()
	var out map[string]any
	_ = json.NewDecoder(res.Body).Decode(&out)
	return out, res.StatusCode, nil
}

// Ask opens a gate and waits for its outcome: approved, denied or expired.
func (c *approvalGateClient) Ask(ctx context.Context, gateType, summary string, details map[string]any, timeout time.Duration) (string, error) {
	status, _, err := c.AskWithID(ctx, gateType, summary, details, timeout)
	return status, err
}

// AskWithID is Ask returning the gate id as well, so a caller can attribute
// the outcome to the gate a human answered (K77 call reports).
func (c *approvalGateClient) AskWithID(ctx context.Context, gateType, summary string, details map[string]any, timeout time.Duration) (status, gateID string, err error) {
	created, code, err := c.do(ctx, http.MethodPost, "/api/tasks/"+c.taskID+"/gates", map[string]any{"gate_type": gateType, "summary": summary, "details": details})
	if err != nil {
		return "", "", err
	}
	if code != http.StatusCreated {
		return "", "", fmt.Errorf("open gate: server answered %d", code)
	}
	gateID, _ = created["id"].(string)
	if gateID == "" {
		return "", "", errors.New("open gate: no id in the answer")
	}
	deadline := time.Now().Add(timeout)
	for {
		if time.Now().After(deadline) {
			return "expired", gateID, nil
		}
		got, code, err := c.do(ctx, http.MethodGet, "/api/tasks/"+c.taskID+"/gates/"+gateID+"?wait=25", nil)
		if err != nil {
			if ctx.Err() != nil {
				return "", gateID, ctx.Err()
			}
			time.Sleep(5 * time.Second)
			continue
		}
		if code != http.StatusOK {
			return "", gateID, fmt.Errorf("poll gate: server answered %d", code)
		}
		if status, _ := got["status"].(string); status != "" && status != "pending" {
			return status, gateID, nil
		}
	}
}

// sensitiveToolMatcher compiles the pattern, falling back to the default.
func sensitiveToolMatcher(pattern string) *regexp.Regexp {
	if pattern == "" {
		pattern = DefaultGateSensitiveTools
	}
	re, err := regexp.Compile(pattern)
	if err != nil {
		return regexp.MustCompile(DefaultGateSensitiveTools)
	}
	return re
}

// gateParamPaths lifts path-like arguments out of a tool call so the
// server can apply the project's blast radius (K07).
func gateParamPaths(params json.RawMessage) []string {
	var in struct {
		Arguments map[string]any `json:"arguments"`
	}
	if json.Unmarshal(params, &in) != nil || in.Arguments == nil {
		return []string{}
	}
	out := []string{}
	for _, key := range []string{"path", "file_path", "filePath", "target", "paths", "files"} {
		switch v := in.Arguments[key].(type) {
		case string:
			if strings.TrimSpace(v) != "" {
				out = append(out, v)
			}
		case []any:
			for _, item := range v {
				if s, ok := item.(string); ok && strings.TrimSpace(s) != "" {
					out = append(out, s)
				}
			}
		}
	}
	return out
}

// applyPermissionProfile (K06) withholds the profile's hidden secrets and
// appends the flags the provider can enforce (Claude deny rules, Codex
// read-only sandbox). It mutates the agent payload once so every later
// reader — env layering, launch args, the MCP gate — sees the same run.
//
// blockSensitiveFiles (JEF-256) is the task's merged sandbox policy asking for
// the .env read block. It applies with or without a permission profile: a nil
// profile means a zero one, whose only deny rules are the sandbox's own.
func applyPermissionProfile(agent *AgentData, provider string, blockSensitiveFiles bool, log *slog.Logger) {
	if agent == nil {
		return
	}
	p := agent.PermissionProfile
	if p == nil {
		if !blockSensitiveFiles {
			return
		}
		zero := permissionprofile.Profile{}
		if extra := zero.ProviderArgsForSandbox(provider, true); len(extra) > 0 {
			agent.CustomArgs = append(append([]string{}, agent.CustomArgs...), extra...)
		}
		return
	}
	var hidden []string
	agent.CustomEnv, hidden = p.FilterSecrets(agent.CustomEnv)
	if len(hidden) > 0 && log != nil {
		log.Info("permission profile: secrets withheld from this run", "profile", p.Name, "keys", hidden)
	}
	if extra := p.ProviderArgsForSandbox(provider, blockSensitiveFiles); len(extra) > 0 {
		agent.CustomArgs = append(append([]string{}, agent.CustomArgs...), extra...)
	}
}

// runSecretResolver (K09) lets the MCP broker trade a run-scoped token for
// its value through the run's own credential. Nil when the run has none.
func (d *Daemon) runSecretResolver(task Task) runSecretResolver {
	token, err := taskScopedAuthToken(task)
	if err != nil || d.client == nil {
		return nil
	}
	return func(ctx context.Context, secretToken string) (string, error) {
		return d.client.ResolveRunSecret(ctx, token, task.ID, secretToken)
	}
}
