import { queryOptions } from "@tanstack/react-query";
import { api } from "../api";
import type { PrWalkthrough } from "./schemas";

// A walkthrough is generated by an agent run, so `pending` resolves later.
// Polling covers the case where the realtime event is missed; the event is the
// fast path, this is the floor.
const POLL_MS = 15_000;

export const prWalkthroughKeys = {
  all: (wsId: string) => ["pr-walkthrough", wsId] as const,
  detail: (wsId: string, issueId: string, prId: string) =>
    ["pr-walkthrough", wsId, issueId, prId] as const,
  settings: (wsId: string) => ["pr-walkthrough-settings", wsId] as const,
};

export function prWalkthroughOptions(wsId: string, issueId: string, prId: string) {
  return queryOptions({
    queryKey: prWalkthroughKeys.detail(wsId, issueId, prId),
    queryFn: () => api.getPrWalkthrough(issueId, prId),
    enabled: !!wsId && !!issueId && !!prId,
    refetchInterval: (query) =>
      (query.state.data as PrWalkthrough | undefined)?.state === "pending" ? POLL_MS : false,
  });
}

export function prWalkthroughSettingsOptions(wsId: string) {
  return queryOptions({
    queryKey: prWalkthroughKeys.settings(wsId),
    queryFn: () => api.getPrWalkthroughSettings(),
    enabled: !!wsId,
  });
}
