import { queryOptions } from "@tanstack/react-query";
import { api } from "../api";
import type { PrWalkthrough } from "./schemas";
import type { AnchoredThreads } from "../types";

// A walkthrough is generated by an agent run, so `pending` resolves later.
// Polling covers the case where the realtime event is missed; the event is the
// fast path, this is the floor.
const POLL_MS = 15_000;

export const prWalkthroughKeys = {
  all: (wsId: string) => ["pr-walkthrough", wsId] as const,
  detail: (wsId: string, issueId: string, prId: string) =>
    ["pr-walkthrough", wsId, issueId, prId] as const,
  settings: (wsId: string) => ["pr-walkthrough-settings", wsId] as const,
  // Comment threads anchored to this pull request's diff (F07). Keyed by head
  // as well as by pull request: the threads a reviewer sees change when the
  // head does, and a cache shared across heads would show the wrong set.
  anchoredThreads: (wsId: string, issueId: string, prId: string, sha: string) =>
    ["pr-anchored-threads", wsId, issueId, prId, sha] as const,
};

export function prWalkthroughOptions(wsId: string, issueId: string, prId: string) {
  return queryOptions({
    queryKey: prWalkthroughKeys.detail(wsId, issueId, prId),
    queryFn: () => api.getPrWalkthrough(issueId, prId),
    enabled: !!wsId && !!issueId && !!prId,
    refetchInterval: (query) =>
      (query.state.data as PrWalkthrough | undefined)?.state === "pending" ? POLL_MS : false,
  });
}

export function prWalkthroughSettingsOptions(wsId: string) {
  return queryOptions({
    queryKey: prWalkthroughKeys.settings(wsId),
    queryFn: () => api.getPrWalkthroughSettings(),
    enabled: !!wsId,
  });
}

/**
 * The anchored discussions of one pull request's diff (F07 / JEF-21).
 *
 * `sha` is optional and, when omitted, every head's threads come back — so a
 * question asked about a revision that has since been pushed over is still
 * shown, marked stale, instead of quietly disappearing the moment someone
 * pushes.
 */
export function anchoredThreadsOptions(wsId: string, issueId: string, prId: string, sha = "") {
  return queryOptions({
    queryKey: prWalkthroughKeys.anchoredThreads(wsId, issueId, prId, sha),
    queryFn: (): Promise<AnchoredThreads> => api.listAnchoredThreads(issueId, prId, sha || undefined),
    enabled: !!wsId && !!issueId && !!prId,
  });
}
